### ISSUE TITLE
大佬  有兴趣搞一个Vue版本的么

### ISSUE THREAD

**Issue by jiumengs** [tjx666/awesome-chrome-extension-boilerplate#11]

**Comment by tjx666** [comment]
等 vue3 发稳定版后有时间就开始搞。

**Comment by jiumengs** [comment]
vue正式版 今天发布啦  /呲牙

**Comment by jiumengs** [comment]
期待vue版本

**Comment by xlzy520** [comment]
[vue3-chrome-extension-boilerplate](https://github.com/xlzy520/vue3-chrome-extension-boilerplate)
 fork了大佬的一份，简单做了一个Vue的适配，可以试试
 @jiumengs

**Comment by tjx666** [comment]
在这讨论： https://github.com/tjx666/awesome-chrome-extension-boilerplate/issues/37
