### ISSUE TITLE
引入 antd v4 异常，大佬能否给导入下

### ISSUE THREAD

**Issue by hsdtsyl** [tjx666/awesome-chrome-extension-boilerplate#3]

**Comment by tjx666** [comment]
明天我在 README 里面补个引入 antd 的教程

**Comment by tjx666** [comment]
可以参考下：[refined-nowcoder](https://github.com/tjx666/refined-nowcoder)

**Comment by tjx666** [comment]
已经集成 ant design https://github.com/tjx666/awesome-chrome-extension-boilerplate/commit/d63c0307c2871fd9b0cbc902af4e60d3d9686960

**Comment by tjx666** [comment]
我估计你导入不了主要是因为这一行代码：https://github.com/tjx666/awesome-chrome-extension-boilerplate/blob/cde14789d561ca3913dfa32c940993b236732a70/server/configs/webpack.common.ts#L48

ant design 的主题色我忘记恢复成默认的了，把这行去掉就行：https://github.com/tjx666/awesome-chrome-extension-boilerplate/blob/master/server/configs/webpack.common.ts#L117

**Comment by hsdtsyl** [comment]
非常赞，感谢高手兄的指导！
我是个后端开发，对前端了解不多。昨天翻了antd的教程，自己也集成成功了。

很期待这个框架的持续改进。
