### ISSUE TITLE
React devtools integration

### ISSUE THREAD

**Issue by lndgalante** [tjx666/awesome-chrome-extension-boilerplate#39]
Hi @tjx666 would like to know if there's any guide or similar to integrate react dev-tools to any chrome extension, ty!

**Comment by tjx666** [comment]
1. add `react-devtools` to webpack entry like https://github.com/tjx666/awesome-chrome-extension-boilerplate/blob/master/server/utils/entry.ts#L28
2. install and start https://www.npmjs.com/package/react-devtools

**Comment by tjx666** [comment]
Or just following https://github.com/facebook/react/tree/main/packages/react-devtools#usage-with-react-dom
