### ISSUE TITLE
支持 webpack dev server 代理和 API mock

### ISSUE THREAD

**Issue by hsdtsyl** [tjx666/awesome-chrome-extension-boilerplate#4]
最近一段时间在用这个脚手架开发插件，作为后端开发，很多前端的东西还是很懵逼的；

大佬有没有时间给折腾下开发环境的代理和跨域问题；

目前我的项目卡到这里啦；

**Comment by tjx666** [comment]
你把你碰到的问题具体描述下，明天或者后天我就把这两个功能给做了。我 TODO 里面说的 webpack dev server 和 API mock 可能并不能满足你当前需求。

**Comment by hsdtsyl** [comment]
昨天为前后端通讯引入了 axios，解决跨域问题后，又碰见 axios 的异步请求问题；
为解决异步请求问题，想引入数据仓库解决，使用 mobx 时，提示装饰器写法不支持，就引入 @babel/plugin-proposal-decorators, 结果与 server 下的 autoreloadclient.ts 冲突；
---
目前大概就是这个状态；不知道你在与后端通讯时如何解决这类问题的；
