### ISSUE TITLE
optimization.splitChunks配置的问题

### ISSUE THREAD

**Issue by Shadowzzh** [tjx666/awesome-chrome-extension-boilerplate#42]
我不太明白为什么只有一些库（例如 Material UI、React 和 React Router）可以成功地拆分为单独的代码块。
而其他不能被拆分，从而导致background.js 和 contentScript.js不能立即执行。

此外，我还尝试使用 runtimeChunk 选项来将运行时代码提取到单独的代码块中，但是单独拆分运行时代码，也会导致background.js 和 contentScript.js不能立即执行。

我明白这个问题不是你的项目的问题，而是关于我对 Webpack 的使用理解不够深入。

**Comment by tjx666** [comment]
没太理解，你可能得贴个仓库地址或者加点图讲详细点

**Comment by Shadowzzh** [comment]
使用`splitChunks`选项和`runtimeChunk`配置时，会导致content功能失效。
但是popup、options、background可以正常运行。

![image](https://github.com/tjx666/awesome-chrome-extension-boilerplate/assets/27343063/1d6d72d1-8d56-4fc0-a374-1f348e03d6b7)

**Comment by Shadowzzh** [comment]
已解决！，因为使用`splitChunks`选项和`runtimeChunk`配置，在wepack.target=web时，会通过html文件引入其他`chunk`。如下；
![image](https://github.com/tjx666/awesome-chrome-extension-boilerplate/assets/27343063/3432fd1e-24cb-4814-bdc6-c17266aed662)

而content.js和backgroud.js没有页面，所以只能另辟蹊径。
我解决方案是使用两套webpack配置，分别配置它们。

主要还是对wepack不够熟悉。
