### ISSUE TITLE
能否在脚手架中，将无状态组件修改为有状态组件，方便开发数据管理

### ISSUE THREAD

**Issue by hsdtsyl** [tjx666/awesome-chrome-extension-boilerplate#5]
如题，我已经在自己的实践中，在 popup 页面，将无状态组件修改为有状态组件啦，其他的还没有动手修改；

**Comment by tjx666** [comment]
不知道呢是否了解 react hooks，函数组件只要使用 hooks 就可以有状态了。

**Comment by tjx666** [comment]
函数组件使用 useState hook 来维持状态的例子，一个简单的计数器：https://github.com/tjx666/react-typescript-boilerplate/blob/master/src/App.tsx。
不过 mobx 貌似一般都是使用 class 组件做开发，我i不可能满足所有用户的需求我觉得将函数组件转换从有状态组件也不是什么困难的事情，甚至简单的情况下可以使用 VSCode 扩展一键转换。
