### ISSUE TITLE
yarn start下使用antd组件报错

### ISSUE THREAD

**Issue by lihuaye** [tjx666/awesome-chrome-extension-boilerplate#7]
```
Uncaught SyntaxError: Unexpected token 'else'
    at Object../node_modules/@ant-design/colors/lib/generate.js
```

yarn build是可以正常使用

**Comment by lihuaye** [comment]
![image](https://user-images.githubusercontent.com/7691792/78418268-433ff800-766d-11ea-9077-8a99d5ad5666.png)

**Comment by tjx666** [comment]
你好，我在本地使用 antd 并没碰到问题，麻烦先试一下最新版，看看有没有解决问题。如果还有问题麻烦提供一个示例仓库或者贴下你出问题的源代码。从你前面的描述中我并没有获取到对解决问题有用的信息。

**Comment by lihuaye** [comment]
> 你好，我在本地使用 antd 并没碰到问题，麻烦先试一下最新版，看看有没有解决问题。如果还有问题麻烦提供一个示例仓库或者贴下你出问题的源代码。从你前面的描述中我并没有获取到对解决问题有用的信息。

更新后可以使用了，万分感谢。
就是在模板基础上使用antd组件后，start编译出来的代码 if 语句块在注释行，导致的错误
