### ISSUE TITLE
start 后修改src里面的文件 生成对应的html文件不会添加js 静态资源

### ISSUE THREAD

**Issue by hechaoqun** [tjx666/awesome-chrome-extension-boilerplate#9]
问一下这个是webpack那个配置项有问题吗

**Comment by hechaoqun** [comment]
![image](https://user-images.githubusercontent.com/21004198/84340810-20354580-abd4-11ea-9754-9a67542257bf.png)

找到了 这里有个copy 逻辑

**Comment by tjx666** [comment]
我没太懂你的意思，可以描述的具体点？

**Comment by hechaoqun** [comment]
globOptions: {
        ignore: ['*.html'],
 },

就是webpack 的这个属性可能不起作用 导致会把html 覆盖过去

**Comment by tjx666** [comment]
fixed: https://github.com/tjx666/awesome-chrome-extension-boilerplate/commit/f4955420db2b4b8d16852a62a1d51bfc1b6ba560#diff-baea4e433198483b6c1ad6b99b79bb4a

**Comment by hechaoqun** [comment]
Nice 非常不错 赞
